Build 1.6.16

diff --git a/roles/adduser/tasks/main.yml b/roles/adduser/tasks/main.yml
--- a/roles/adduser/tasks/main.yml
+++ b/roles/adduser/tasks/main.yml
@@ -1,11 +1,15 @@
 ---
 
 - name: Add User
-  shell: ../scripts/add.user.sh "{{ args_ipaddress }}" "{{ args_install_username }}" "{{ args_admin_username }}" "{{ args_admin_password }}"
+  shell: |
+    {{ role_path }}/scripts/add.user.sh "{{ prop_ipaddress }}" "{{ prop_install_username }}" "{{ prop_admin_username }}" "{{ prop_admin_password }}"
+    if [[ "$?" != "0" ]]; then
+      echo "Error executing script" 
+    fi
   args:
     executable: /bin/bash
   register: expectresult
   changed_when: '"Changed" in expectresult.stdout'
-  failed_when: '"Error" in expectresult.stdout'
+  failed_when: '("Error" in expectresult.stdout) or ("Host key verification failed." in expectresult.stdout)'
   connection: local
   become: false
diff --git a/roles/autologon/tasks/main.yml b/roles/autologon/tasks/main.yml
--- a/roles/autologon/tasks/main.yml
+++ b/roles/autologon/tasks/main.yml
@@ -1,7 +1,11 @@
 ---
 
 - name: Ensure autologon
-  shell: ../scripts/auto.logon.sh "{{ args_ipaddress }}" "{{ args_admin_username }}" "{{ args_admin_password }}" "{{ args_local_user_ssh_key }}" "{{ args_local_user_ssh_pub }}" "{{ args_autologon_expect }}"
+  shell: |
+    {{ role_path }}/scripts/auto.logon.sh "{{ prop_ipaddress }}" "{{ prop_admin_username }}" "{{ prop_admin_password }}" "{{ prop_local_user_ssh_key }}" "{{ prop_local_user_ssh_pub }}" "{{ prop_autologon_expect }}"
+    if [[ "$?" != "0" ]]; then
+      echo "Error executing script" 
+    fi
   args:
     executable: /bin/bash
   register: expectresult
diff --git a/roles/firstlogon/tasks/main.yml b/roles/firstlogon/tasks/main.yml
--- a/roles/firstlogon/tasks/main.yml
+++ b/roles/firstlogon/tasks/main.yml
@@ -1,11 +1,15 @@
 ---
 
 - name: First logon
-  shell: ../scripts/first.logon.sh "{{ args_ipaddress }}" "{{ args_admin_password }}" "{{ args_firstlogon_expect }}" "{{ args_install_username }}" "{{ args_install_password }}"
+  shell: |
+    {{ role_path }}/scripts/first.logon.sh "{{ prop_ipaddress }}" "{{ prop_admin_password }}" "{{ prop_firstlogon_expect }}" "{{ prop_install_username }}" "{{ prop_install_password }}"
+    if [[ "$?" != "0" ]]; then
+      echo "Error executing script" 
+    fi
   args:
     executable: /bin/bash
   register: expectresult
   changed_when: '"Changed" in expectresult.stdout'
-  failed_when: '"Error" in expectresult.stdout'
+  failed_when: '("Error" in expectresult.stdout) or ("Host key verification failed." in expectresult.stdout)'
   connection: local
   become: false
diff --git a/roles/knownhost/tasks/main.yml b/roles/knownhost/tasks/main.yml
--- a/roles/knownhost/tasks/main.yml
+++ b/roles/knownhost/tasks/main.yml
@@ -1,11 +1,15 @@
 ---
 
 - name: Update Known Hosts
-  shell: ../scripts/known.hosts.sh "{{ args_ipaddress }}" "{{ args_local_user_ssh }}"
+  shell: |
+    {{ role_path }}/scripts/known.hosts.sh "{{ args_ipaddress }}" "{{ prop_local_user_ssh }}"
+    if [[ "$?" != "0" ]]; then
+      echo "Error executing script" 
+    fi
   args:
     executable: /bin/bash
-  register: expectresult
-  changed_when: '"Changed" in expectresult.stdout'
-  failed_when: '"Error" in expectresult.stdout'
+  register: result
+  changed_when: '"Changed" in result.stdout'
+  failed_when: '"Error" in result.stdout'
   connection: local
   become: false
diff --git a/roles/remoteinstallpython3/tasks/main.yml b/roles/remoteinstallpython3/tasks/main.yml
--- a/roles/remoteinstallpython3/tasks/main.yml
+++ b/roles/remoteinstallpython3/tasks/main.yml
@@ -1,7 +1,11 @@
 ---
 
 - name: Remote install python3
-  shell: ../scripts/remote.install.python3.sh "{{ args_ipaddress }}" "{{ args_admin_username }}"
+  shell: |
+    {{ role_path }}/scripts/remote.install.python3.sh "{{ prop_ipaddress }}" "{{ prop_admin_username }}"
+    if [[ "$?" != "0" ]]; then
+      echo "Error executing script" 
+    fi
   args:
     executable: /bin/bash
   register: expectresult
diff --git a/roles/remoteinstallsudo/tasks/main.yml b/roles/remoteinstallsudo/tasks/main.yml
--- a/roles/remoteinstallsudo/tasks/main.yml
+++ b/roles/remoteinstallsudo/tasks/main.yml
@@ -1,7 +1,11 @@
 ---
 
 - name: Remote install sudo
-  shell: ../scripts/remote.install.sudo.sh "{{ args_ipaddress }}" "{{ args_install_username }}" "{{ args_admin_password }}" "{{ args_expect }}"
+  shell: |
+    {{ role_path }}/scripts/remote.install.sudo.sh "{{ prop_ipaddress }}" "{{ prop_install_username }}" "{{ prop_admin_password }}" "{{ prop_expect }}"
+    if [[ "$?" != "0" ]]; then
+      echo "Error executing script" 
+    fi
   args:
     executable: /bin/bash
   register: expectresult
diff --git a/roles/sudouser/tasks/main.yml b/roles/sudouser/tasks/main.yml
--- a/roles/sudouser/tasks/main.yml
+++ b/roles/sudouser/tasks/main.yml
@@ -1,7 +1,11 @@
 ---
 
 - name: Set sudo for user
-  shell: ../scripts/sudo.user.sh "{{ args_ipaddress }}" "{{ args_admin_username }}" "{{ args_admin_password }}"
+  shell: |
+    {{ role_path }}/scripts/sudo.user.sh "{{ prop_ipaddress }}" "{{ prop_admin_username }}" "{{ prop_admin_password }}"
+    if [[ "$?" != "0" ]]; then
+      echo "Error executing script" 
+    fi
   args:
     executable: /bin/bash
   register: expectresult
